// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW3L-bX3fRHzaVNtiCStylPX4rFYaJeks',
    appId: '1:258908903670:web:cf93f5546ef7cf0cc134d7',
    messagingSenderId: '258908903670',
    projectId: 'devfest-cairo',
    authDomain: 'devfest-cairo.firebaseapp.com',
    storageBucket: 'devfest-cairo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcpGYI00V7pO8lm7Yp_4Dwt06mJFbjhNw',
    appId: '1:258908903670:android:c3b393fb7a55ec0dc134d7',
    messagingSenderId: '258908903670',
    projectId: 'devfest-cairo',
    storageBucket: 'devfest-cairo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHv53fKb6lXQpSBSp31FdmNK740nHJoBM',
    appId: '1:258908903670:ios:bba2fdd78b071828c134d7',
    messagingSenderId: '258908903670',
    projectId: 'devfest-cairo',
    storageBucket: 'devfest-cairo.firebasestorage.app',
    iosBundleId: 'com.mahmoudalaa.aiDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHv53fKb6lXQpSBSp31FdmNK740nHJoBM',
    appId: '1:258908903670:ios:bba2fdd78b071828c134d7',
    messagingSenderId: '258908903670',
    projectId: 'devfest-cairo',
    storageBucket: 'devfest-cairo.firebasestorage.app',
    iosBundleId: 'com.mahmoudalaa.aiDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW3L-bX3fRHzaVNtiCStylPX4rFYaJeks',
    appId: '1:258908903670:web:e9de5d1ea293c675c134d7',
    messagingSenderId: '258908903670',
    projectId: 'devfest-cairo',
    authDomain: 'devfest-cairo.firebaseapp.com',
    storageBucket: 'devfest-cairo.firebasestorage.app',
  );

}