// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiao-oVHppoh8b1kVx0RHC0FDtWVLLF_8',
    appId: '1:675927201984:web:63c5ce3312fe5cab1ab525',
    messagingSenderId: '675927201984',
    projectId: 'ai-demo-devfest',
    authDomain: 'ai-demo-devfest.firebaseapp.com',
    storageBucket: 'ai-demo-devfest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdDJDUjDNL3otiLgGN0m24jc0rHMiykZ4',
    appId: '1:675927201984:android:641ce527ceb33d231ab525',
    messagingSenderId: '675927201984',
    projectId: 'ai-demo-devfest',
    storageBucket: 'ai-demo-devfest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVXUfacEvQ4PAqk76Petx77HYFJAxsXwk',
    appId: '1:675927201984:ios:11ecac3eba56ed421ab525',
    messagingSenderId: '675927201984',
    projectId: 'ai-demo-devfest',
    storageBucket: 'ai-demo-devfest.firebasestorage.app',
    iosBundleId: 'com.mahmoudalaa.aiDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVXUfacEvQ4PAqk76Petx77HYFJAxsXwk',
    appId: '1:675927201984:ios:11ecac3eba56ed421ab525',
    messagingSenderId: '675927201984',
    projectId: 'ai-demo-devfest',
    storageBucket: 'ai-demo-devfest.firebasestorage.app',
    iosBundleId: 'com.mahmoudalaa.aiDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiao-oVHppoh8b1kVx0RHC0FDtWVLLF_8',
    appId: '1:675927201984:web:ab219286b4b8018b1ab525',
    messagingSenderId: '675927201984',
    projectId: 'ai-demo-devfest',
    authDomain: 'ai-demo-devfest.firebaseapp.com',
    storageBucket: 'ai-demo-devfest.firebasestorage.app',
  );
}
